# Generated by Django 5.2.17 on 2026-08-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
