# Generated by Django 5.2.17 on 2026-08-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_asset_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='property_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
