# Generated by Django 5.2.17 on 2026-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_asset_property_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_REPAIR', 'In Repair'), ('IN_STORAGE', 'In Storage'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20),
        ),
    ]
