# Generated by Django 5.2.17 on 2026-08-25 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_asset_warranty_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.asset')),
            ],
        ),
    ]
