# Generated by Django 5.2.17 on 2026-08-25 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_specificationdefinition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetspecification',
            name='specifications',
        ),
        migrations.AddField(
            model_name='assetspecification',
            name='definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.specificationdefinition'),
        ),
        migrations.AddField(
            model_name='assetspecification',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assetspecification',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asset'),
        ),
    ]
