# Generated by Django 5.2.17 on 2026-08-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_assetspecification_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetspecification',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.specificationdefinition'),
        ),
    ]
