# Generated by Django 5.2.17 on 2026-08-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_assetspecification_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='used_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unit'),
        ),
    ]
