# Generated by Django 5.2.17 on 2026-08-25 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_category_options_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHandling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handled_date', models.DateField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.request')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.personnel')),
            ],
        ),
    ]
