# Generated by Django 5.2.17 on 2026-08-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_requesthandling_external_repair_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthandling',
            name='warranty_status',
            field=models.CharField(blank=True, choices=[('UNDER_WARRANTY', 'Under Warranty'), ('EXPIRED', 'Warranty Expired'), ('NOT_COVERED', 'Not Covered')], max_length=20),
        ),
    ]
