# Generated by Django 5.2.17 on 2026-08-26 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_requesthandling_warranty_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesthandling',
            name='warranty_status',
        ),
    ]
