# Generated by Django 5.2.17 on 2026-08-26 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_requesthandling_warranty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthandling',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.asset'),
        ),
    ]
