# Generated by Django 5.2.17 on 2026-08-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_requesthandling_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthandling',
            name='external_approval',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', max_length=20),
        ),
    ]
