# Generated by Django 5.2.17 on 2026-08-27 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_requesthandling_external_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthandling',
            name='replacement_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_for', to='core.asset'),
        ),
        migrations.AddField(
            model_name='requesthandling',
            name='replacement_type',
            field=models.CharField(blank=True, choices=[('TEMPORARY', 'Temporary Replacement'), ('PERMANENT', 'Permanent Replacement')], max_length=20),
        ),
    ]
