# Generated by Django 5.2.17 on 2026-08-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_requesthandling_replacement_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthandling',
            name='next_action',
            field=models.CharField(choices=[('NONE', 'None / Finished'), ('WORKSHOP', 'IT Workshop'), ('EXTERNAL', 'External Repair'), ('REPLACEMENT', 'Replacement')], default='NONE', max_length=20),
        ),
    ]
