
# Generated by Django 5.2.17 on 2026-09-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_requesthandling_external_repair_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.CreateModel(
            name='Requester',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'name',
                    models.CharField(max_length=100)
                ),
                (
                    'phone',
                    models.CharField(
                        blank=True,
                        max_length=30
                    )
                ),
                (
                    'email',
                    models.EmailField(
                        blank=True,
                        max_length=254
                    )
                ),
                (
                    'is_active',
                    models.BooleanField(default=True)
                ),
                (
                    'notes',
                    models.TextField(blank=True)
                ),
                (
                    'unit',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='core.unit'
                    )
                ),
                (
                    'user',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
        ),

        migrations.AddField(
            model_name='request',
            name='attachment',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='request_attachments/'
            ),
        ),

        migrations.AddField(
            model_name='request',
            name='requester_profile',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='requests',
                to='core.requester'
            ),
        ),
    ]