# Generated by Django 5.2.17 on 2026-09-09 20:34

from django.db import migrations


def create_location_hierarchy(apps, schema_editor):
    Location = apps.get_model("core", "Location")

    # ---------------------------------------------------------
    # Building 1
    # ---------------------------------------------------------
    building_1, _ = Location.objects.get_or_create(
        name="Building 1",
        location_type="BUILDING",
        parent=None,
        defaults={
            "description": "",
            "is_active": True,
        },
    )

    floor_2, _ = Location.objects.get_or_create(
        name="Floor 2",
        location_type="FLOOR",
        parent=building_1,
        defaults={
            "description": "",
            "is_active": True,
        },
    )

    # IMPORTANT:
    # Keep the existing Location ID 2 because
    # IT-000002 currently points to it.
    old_location_2 = Location.objects.get(
        pk=2
    )

    old_location_2.name = "IT Storage Room"
    old_location_2.location_type = "AREA"
    old_location_2.parent = floor_2
    old_location_2.save()


    # ---------------------------------------------------------
    # Building 6
    # ---------------------------------------------------------
    building_6, _ = Location.objects.get_or_create(
        name="Building 6",
        location_type="BUILDING",
        parent=None,
        defaults={
            "description": "",
            "is_active": True,
        },
    )

    floor_3, _ = Location.objects.get_or_create(
        name="Floor 3",
        location_type="FLOOR",
        parent=building_6,
        defaults={
            "description": "",
            "is_active": True,
        },
    )

    # IMPORTANT:
    # Keep the existing Location ID 1 because
    # IT-000001 currently points to it.
    old_location_1 = Location.objects.get(
        pk=1
    )

    old_location_1.name = "Main IT Storage Room"
    old_location_1.location_type = "AREA"
    old_location_1.parent = floor_3
    old_location_1.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0031_alter_category_options_location_location_type_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            create_location_hierarchy,
            migrations.RunPython.noop,
        ),
    ]