# Generated by Django 5.2.17 on 2026-09-14 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20260910_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('contract_type', models.CharField(choices=[('INTERNET', 'Internet / Network Service'), ('MAINTENANCE', 'Maintenance'), ('SOFTWARE', 'Software'), ('SUPPORT', 'Support'), ('EQUIPMENT_SERVICE', 'Equipment / Service'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('provider', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unit')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-start_date', 'title'],
            },
        ),
    ]
